
namespace Paratranz.NET.Test
{
    [TestFixture]
    public class ParatranzServiceProjectTest
    {
        ParatranzService Service;
        int AutomaticallyCreatedProjectId;

        #region Initialize Test

        [OneTimeSetUp]
        public void SetUp()
        {
            var apiToken = Environment.GetEnvironmentVariable("API_TOKEN");
            Assert.IsNotNull(apiToken);

            var client = new ParatranzClient(apiToken);
            Service = new ParatranzService(client);
        }

        [OneTimeTearDown]
        public void TearDown()
        {
            Service.Dispose();
        }

        #endregion // Initialize Test

        [Test, Order(0)]
        public async Task CreateProjectTest()
        {
            var projectRequest = new C2S_ProjectRequest
            {
                Name = "Test Paratranz Project",
                Logo = new Uri("https://paratranz.cn/assets/logo-B84VfjuK.svg"),
                Desc = "Automatically generated by NUnit tests in Paratranz.NET.",
                Source = "en",
                Dest = "kr",
                Game = "hoi4",
                Privacy = 0,
                Download = 0,
                IssueMode = 0,
                ReviewMode = 0,
                JoinMode = 0,
            };

            try
            {
                var res = await Service.CreateProjectAsync(projectRequest, default);
                Assert.IsNotNull(res, "Name:{0}", projectRequest.Name);
                AutomaticallyCreatedProjectId = res.Id;
            }
            catch (Exception ex)
            {
                Assert.Fail("Fail:{0}", ex.Message);
            }
        }

        [Test, Order(1)]
        public async Task UpdateProjectTest()
        {
            var projectRequest = new C2S_ProjectRequest
            {
                Name = "Test Paratranz Project",
                Logo = new Uri("https://paratranz.cn/assets/logo-B84VfjuK.svg"),
                Desc = "Automatically generated by NUnit tests in Paratranz.NET.",
                Source = "kr",
                Dest = "en",
                Game = "hoi4",
                Privacy = 0,
                Download = 0,
                IssueMode = 0,
                ReviewMode = 0,
                JoinMode = 0,
            };

            try
            {
                var res = await Service.UpdateProjectAsync(AutomaticallyCreatedProjectId, projectRequest, default);
                Assert.IsNotNull(res, "projectId:{0}", AutomaticallyCreatedProjectId);
            }
            catch (Exception ex)
            {
                Assert.Fail("Fail:{0}", ex.Message);
            }
        }

        [Test, Order(2)]
        public async Task DeleteProjectTest()
        {
            try
            {
                var res = await Service.DeleteProjectAsync(AutomaticallyCreatedProjectId, default);
                Assert.IsTrue(res, "projectId:{0}", AutomaticallyCreatedProjectId);
            }
            catch (Exception ex)
            {
                Assert.Fail("Fail:{0}", ex.Message);
            }
        }

        [TestCase(2445)] // Equestria at War Korean Translation
        [TestCase(3824)] // Hearts of Iron 4 Korean Translation
        [TestCase(8477)] // Pdx-Unlimiter Korean
        [TestCase(9106)] // Old World Blues Korean
        public async Task GetProjectTest(int projectId)
        {
            var res = await Service.GetProjectAsync(projectId, default);
            Assert.IsNotNull(res, "projectId: {0}", projectId);
        }


    }
}